import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorker} from '../server/worker.js';
const worker=createWorker('landing','admin','callback');
const user={id:'00000000-0000-4000-8000-000000000001',email:'fixture@example.test',email_confirmed_at:'2026-01-01',user_metadata:{name:'테스트',phone:'01000000000'},app_metadata:{}};
const session={user,access_token:'access-fixture',refresh_token:'refresh-fixture',expires_in:3600};
function env(handler){return {SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_fixture',SUPABASE_SECRET_KEY:'sb_secret_fixture',FETCH:async(url,opts)=>{const output=await handler(new URL(url),opts);return output instanceof Response?output:Response.json(output);}};}
const request=(path,payload,headers={})=>new Request('https://site.example'+path,{method:payload?'POST':'GET',headers:{'Content-Type':'application/json',...headers},...(payload?{body:JSON.stringify(payload)}:{})});
test('missing configuration fails rather than reporting a saved lead',async()=>{const r=await worker.fetch(request('/api/campaign/hokyung',{action:'init'}),{});assert.equal(r.status,503);assert.match((await r.json()).error,/저장되지/);});
test('signup forwards password only to Auth and emits only HttpOnly cookies',async()=>{const calls=[];const e=env((url,o)=>{calls.push({url,o});return session;});const r=await worker.fetch(request('/api/auth/signup',{email:user.email,password:'fixturePassword123!',name:'테스트',phone:'010-0000-0000',consent:true}),e);assert.equal(r.status,200);const data=await r.json();assert.equal(data.user.admin,false);assert.equal(data.access_token,undefined);assert.equal(data.refresh_token,undefined);assert.equal(calls.length,1);assert.equal(calls[0].url.pathname,'/auth/v1/signup');const sent=JSON.parse(calls[0].o.body);assert.equal(sent.password,'fixturePassword123!');assert.deepEqual(sent.data,{name:'테스트',phone:'01000000000'});assert.ok(r.headers.getSetCookie().every(v=>v.includes('HttpOnly')&&v.includes('Secure')&&v.includes('SameSite=Lax')));});
test('confirmation signup does not log in an unverified account',async()=>{const r=await worker.fetch(request('/api/auth/signup',{email:user.email,password:'fixturePassword123!',name:'테스트',phone:'01000000000',consent:true}),env(()=>({user})));const data=await r.json();assert.equal(data.user,null);assert.equal(data.confirmationRequired,true);assert.ok(r.headers.getSetCookie().every(v=>!v.startsWith('sb_access=')));});
test('user_metadata administrator spoof is rejected before DB query',async()=>{let count=0;const r=await worker.fetch(request('/api/admin/leads',null,{cookie:'sb_access=fixture'}),env(()=>{count++;return {...user,user_metadata:{role:'admin',admin:true}};}));assert.equal(r.status,403);assert.equal(count,1);});
test('verified app_metadata administrator may query safe profile fields',async()=>{let count=0;const r=await worker.fetch(request('/api/admin/members',null,{cookie:'sb_access=fixture'}),env((url,o)=>{count++;if(url.pathname==='/auth/v1/user')return {...user,app_metadata:{role:'admin'}};assert.equal(url.searchParams.get('select'),'id,name,phone,email,created_at');assert.equal(o.headers.apikey,'sb_secret_fixture');assert.equal(o.headers.Authorization,undefined);return [];}));assert.equal(r.status,200);assert.equal(count,2);});
test('completion requires verified login and never trusts client identity',async()=>{const payload={action:'complete',name:'테스트',phone:'01000000000',consent:true,user_id:'attacker',email:'spoof@example.test'};assert.equal((await worker.fetch(request('/api/campaign/hokyung',payload),env(()=>{throw Error('must not fetch');}))).status,401);const r=await worker.fetch(request('/api/campaign/hokyung',payload,{cookie:'sb_access=fixture; flow_hokyung=12345678-1234-1234-1234-123456789012'}),env((url,o)=>{if(url.pathname==='/auth/v1/user')return user;const p=JSON.parse(o.body);assert.equal(p.p_actor,user.id);assert.equal(p.p_email,user.email);assert.equal(p.p_session_hash.length,64);return {completed:true};}));assert.equal(r.status,200);});
test('cross origin mutation is rejected without provider access',async()=>{const r=await worker.fetch(request('/api/auth/login',{email:user.email,password:'fixturePassword123!'},{origin:'https://evil.test'}),env(()=>{throw Error('must not fetch');}));assert.equal(r.status,403);});
test('callback rejects missing state and mismatched access/refresh owners',async()=>{let count=0;const e=env(url=>{count++;return url.pathname==='/auth/v1/user'?user:{...session,user:{...user,id:'other'}};});const payload={state:'fixture-state',access_token:'a',refresh_token:'b'};assert.equal((await worker.fetch(request('/api/auth/session',payload),e)).status,400);assert.equal(count,0);const r=await worker.fetch(request('/api/auth/session',payload,{cookie:'auth_state=fixture-state'}),e);assert.equal(r.status,400);assert.equal(r.headers.getSetCookie().length,0);});
test('expired session refresh replaces cookies without leaking tokens',async()=>{const r=await worker.fetch(request('/api/auth/session',null,{cookie:'sb_access=expired; sb_refresh=fixture'}),env(url=>url.pathname==='/auth/v1/user'?Response.json({error_code:'bad_jwt'},{status:401}):session));assert.equal(r.status,200);assert.equal((await r.json()).user.email,user.email);assert.equal(r.headers.getSetCookie().length,2);});
test('other account completed visit rotates the anonymous visit cookie',async()=>{let rpc=0;const r=await worker.fetch(request('/api/campaign/hokyung',{action:'init'},{cookie:'flow_hokyung=12345678-1234-1234-1234-123456789012'}),env(()=>++rpc===1?Response.json({message:'visit_owner_mismatch'},{status:403}):{step:0,answers:[null,null],completed:false}));assert.equal(r.status,200);assert.equal(rpc,2);assert.match(r.headers.get('set-cookie'),/flow_hokyung=/);});
test('private source and env files are never served',async()=>{for(const path of ['/.env','/server/supabase.js','/scripts/create-admin.mjs'])assert.equal((await worker.fetch(request(path),{})).status,404);});
