const $=id=>document.getElementById(id);
let offset=0,rows=[],busy=false;
const leadColumns=[['created_at','방문 일시'],['campaign','캠페인'],['completed','완료'],['step','저장 단계'],['answer1','채무액'],['answer2','월 소득'],['name','이름'],['phone','연락처'],['email','이메일'],['updated_at','마지막 저장'],['attribution','유입 정보']];
const memberColumns=[['created_at','가입 일시'],['name','이름'],['phone','연락처'],['email','이메일']];
const columns=()=>$('view').value==='members'?memberColumns:leadColumns;
const display=(row,key)=>key==='completed'?(row[key]?'완료':'미완료'):key.endsWith('_at')?(row[key]?new Date(row[key]).toLocaleString('ko-KR'):''):key==='attribution'?JSON.stringify(row[key]||{}):String(row[key]??'');
function message(text){$('message').textContent=text;$('message').hidden=!text;}
async function request(path,payload){const r=await fetch(path,{method:payload?'POST':'GET',headers:{'Content-Type':'application/json'},...(payload?{body:JSON.stringify(payload)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'요청에 실패했습니다.');return d;}
function lock(value){busy=value;document.querySelectorAll('button,select,input').forEach(el=>el.disabled=value);if(!value){$('prev').disabled=offset===0;$('next').disabled=rows.length<100;}}
function showUser(user){const allowed=!!user?.admin;$('login').hidden=allowed;$('dashboard').hidden=!allowed;$('logout').hidden=!user;if(user&&!allowed)message('관리자 권한이 없는 계정입니다. 관리자 계정으로 다시 로그인해 주세요.');return allowed;}
function render(){const head=document.createElement('tr');for(const[,title]of columns()){const th=document.createElement('th');th.textContent=title;head.append(th);}$('columns').replaceChildren(head);const fragment=document.createDocumentFragment();for(const row of rows){const tr=document.createElement('tr');for(const[key]of columns()){const td=document.createElement('td');td.textContent=display(row,key);if(key==='attribution')td.className='wrap';tr.append(td);}fragment.append(tr);}if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=columns().length;td.textContent='조회된 내역이 없습니다.';tr.append(td);fragment.append(tr);}$('rows').replaceChildren(fragment);$('page').textContent=`${offset/100+1} 페이지 · ${rows.length}건`;$('status').hidden=$('view').value==='members';}
async function load(){if(busy)return;lock(true);message('');rows=[];render();try{const {user}=await request('/api/auth/session');if(!showUser(user))return;const data=await request(`/api/admin/${$('view').value}?offset=${offset}&status=${encodeURIComponent($('status').value)}`);rows=data.rows;render();}catch(e){message(e.message);}finally{lock(false);}}
$('login-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const form=e.currentTarget;const payload={email:form.elements.email.value,password:form.elements.password.value};form.elements.password.value='';lock(true);message('');let allowed=false;try{allowed=showUser((await request('/api/auth/login',payload)).user);}catch(e){message(e.message);}finally{payload.password='';lock(false);}if(allowed)await load();};
$('logout').onclick=async()=>{if(busy)return;lock(true);try{await request('/api/auth/logout',{});rows=[];render();showUser(null);message('');}catch(e){message(e.message);}finally{lock(false);}};
for(const id of ['view','status'])$(id).onchange=()=>{offset=0;load();};$('refresh').onclick=load;$('prev').onclick=()=>{offset=Math.max(0,offset-100);load();};$('next').onclick=()=>{offset+=100;load();};
$('download').onclick=()=>{const safe=value=>'"'+String(value).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const csv=[columns().map(([,title])=>safe(title)).join(','),...rows.map(row=>columns().map(([key])=>safe(display(row,key))).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`hokyung-${$('view').value}-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
load();
