const QUESTIONS=[{title:'현재 채무액은 얼마인가요?',description:'현재 총 채무액에 가까운 구간을 선택해 주세요.',options:['1천만 원 미만','1천만 ~ 3천만 원 미만','3천만 ~ 5천만 원 미만','5천만 ~ 1억 원 미만','1억 원 이상']},{title:'월 소득은 얼마인가요?',description:'한 달 평균 실수령액에 가까운 구간을 선택해 주세요.',options:['현재 소득 없음','100만 원 미만','100만 ~ 200만 원 미만','200만 ~ 300만 원 미만','300만 원 이상']}];
const campaign=location.pathname.split('/')[2],body=document.querySelector('#body'),errorBox=document.querySelector('#error');
let state={step:0,answers:[null,null],completed:false,reference:null},step=0,answers=[null,null],ready=false,busy=false,name='',phone='',consent=false;
let authUser=null,authMode='signup',email='';
async function authRequest(action,payload){const r=await fetch('/api/auth/'+action,{method:payload?'POST':'GET',headers:{'Content-Type':'application/json'},...(payload?{body:JSON.stringify(payload)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'인증에 실패했습니다.');return data;}
function showAccount(){const el=document.querySelector('#account');el.textContent=authUser?authUser.email+' · 로그아웃':'';el.hidden=!authUser;el.onclick=async()=>{try{await authRequest('logout',{});authUser=null;name='';phone='';email='';consent=false;showAccount();await init();}catch(e){showError(e.message);}};}
function renderContact(){
 body.innerHTML=`<form id="contact" style="display:flex;flex-direction:column;flex:1"><div class="fade"><span class="badge">마지막 단계</span><h2 tabindex="-1">${authUser?'상담 신청을 마무리하세요.':authMode==='signup'?'회원가입하고<br>상담을 신청하세요.':'로그인하고<br>상담을 신청하세요.'}</h2><p class="sub">이메일이 아이디입니다. 비밀번호는 본인만 알 수 있도록 설정해 주세요.</p>${!authUser?`<div class="auth-tabs"><button type="button" id="signup-tab" aria-pressed="${authMode==='signup'}">회원가입</button><button type="button" id="login-tab" aria-pressed="${authMode==='login'}">로그인</button></div>`:''}<label class="form-field">이름<input name="name" autocomplete="name" required minlength="2" maxlength="50" value="${esc(name)}"></label><label class="form-field">연락처<input name="phone" type="tel" autocomplete="tel" inputmode="tel" placeholder="010-0000-0000" required maxlength="14" value="${esc(phone)}"></label><label class="form-field">이메일 (아이디)<input name="email" type="email" autocomplete="username" required maxlength="254" value="${esc(authUser?.email||email)}" ${authUser?'readonly':''}></label>${!authUser?`<label class="form-field">비밀번호<input name="password" type="password" autocomplete="${authMode==='signup'?'new-password':'current-password'}" required minlength="8" maxlength="128" placeholder="8자 이상"></label>${authMode==='signup'?'<label class="form-field">비밀번호 확인<input name="confirm" type="password" autocomplete="new-password" required minlength="8" maxlength="128"></label>':'<button type="button" id="recover" class="back">비밀번호를 잊으셨나요?</button>'}`:''}<label class="consent"><input type="checkbox" name="consent" required ${consent?'checked':''}><span><b>[필수]</b> 개인정보 수집 및 이용에 동의합니다.</span></label><details class="privacy"><summary>수집 및 이용 내용 보기</summary><p><b>수집·이용 주체:</b> 법무법인 호경<br><b>목적:</b> 회원 식별, 상담 접수 및 연락<br><b>항목:</b> 이름, 연락처, 이메일, 현재 채무액, 월 소득, 동의 시각<br><b>보유기간:</b> 수집일로부터 1년<br>비밀번호는 인증 서비스에서 처리하며 상담 DB나 관리자 화면에 표시하지 않습니다. 동의를 거부할 수 있으나 가입 및 신청이 제한됩니다.</p></details></div><div class="spacer"></div><button class="primary" id="submit" type="submit">${authUser?'상담 신청하기':authMode==='signup'?'회원가입 후 상담 신청':'로그인 후 상담 신청'}</button><p class="smallnote">이메일 인증이 필요하면 인증 후 신청을 마무리해 주세요.</p></form>`;
 const form=document.querySelector('#contact');form.elements.phone.pattern='01[016789][- ]?[0-9]{3,4}[- ]?[0-9]{4}';
 form.addEventListener('input',()=>{name=form.elements.name.value;phone=form.elements.phone.value;email=form.elements.email.value;consent=form.elements.consent.checked;});
 for(const mode of ['signup','login']){const b=document.querySelector('#'+mode+'-tab');if(b)b.onclick=()=>{authMode=mode;clearError();render();};}
 const recovery=document.querySelector('#recover');if(recovery)recovery.onclick=async()=>{if(busy)return;busy=true;busyUI();try{const d=await authRequest('recover',{email:form.elements.email.value,campaign});showError(d.message);}catch(e){showError(e.message);}finally{busy=false;busyUI();}};
 form.onsubmit=async e=>{e.preventDefault();if(busy||!form.reportValidity())return;clearError();
  if(!authUser&&authMode==='signup'&&form.elements.password.value!==form.elements.confirm.value){showError('비밀번호가 일치하지 않습니다.');return;}
  busy=true;busyUI();
  try{
   if(!authUser){const payload={name,phone,email,password:form.elements.password.value,consent,campaign};form.elements.password.value='';if(form.elements.confirm)form.elements.confirm.value='';const result=await authRequest(authMode,payload);payload.password='';if(!result.user){authMode='login';busy=false;render();showError(result.message);return;}authUser=result.user;}
   else{authUser=(await authRequest('session')).user;if(!authUser){authMode='login';busy=false;render();showError('다시 로그인해 주세요.');return;}}
   showAccount();busy=false;const result=await save({action:'complete',name,phone,consent});if(result?.completed){name='';phone='';consent=false;step=4;render();}else render();
  }catch(e){showError(e.message);}finally{busy=false;busyUI();}
 };
}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={sliders:'<path d="M4 7h9m4 0h3M4 17h3m4 0h9"/><circle cx="15" cy="7" r="2"/><circle cx="9" cy="17" r="2"/>',chat:'<path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8v.5Z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'};
const icon=k=>`<svg viewBox="0 0 24 24" width="21" height="21" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[k]}</svg>`;
function showError(message){errorBox.textContent=message;errorBox.hidden=false;if(!ready){const b=document.createElement('button');b.className='retry';b.textContent='다시 연결하기';b.onclick=init;errorBox.append(b);}}
function clearError(){errorBox.hidden=true;errorBox.textContent='';}
function busyUI(){document.querySelector('#card').setAttribute('aria-busy',String(busy));document.querySelectorAll('#body button,#body input,#back').forEach(el=>el.disabled=busy);const next=document.querySelector('#next');if(next)next.disabled=busy||!ready||(step>0&&step<3&&!answers[step-1]);const submit=document.querySelector('#submit');if(submit)submit.textContent=busy?'처리하고 있어요…':authUser?'상담 신청하기':authMode==='signup'?'회원가입 후 상담 신청':'로그인 후 상담 신청';}
async function save(payload){if(busy)return null;busy=true;clearError();busyUI();try{const response=await fetch('/api/campaign/'+encodeURIComponent(campaign),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'저장에 실패했습니다. 다시 시도해 주세요.');state=data;return data;}catch(error){showError(error.message||'연결을 확인하고 다시 시도해 주세요.');return null;}finally{busy=false;busyUI();}}
async function init(){try{authUser=(await authRequest('session')).user;if(authUser){name=authUser.name||name;phone=authUser.phone||phone;}showAccount();}catch(e){showError(e.message);}const data=await save({action:'init',attribution:Object.fromEntries(new URLSearchParams(location.search))});if(data){ready=true;answers=data.answers;step=data.step;render(false);}}
async function next(){const currentStep=step;const data=await save(step===0?{action:'start'}:{action:'answer',question:step-1,value:answers[step-1]});if(data){step=data.completed?4:currentStep+1;render();}}
function choose(value){if(busy||step<1||step>2||!QUESTIONS[step-1].options.includes(value))throw Error('현재 질문의 올바른 답변을 선택해 주세요.');answers[step-1]=value;document.querySelectorAll('.option').forEach(b=>{const chosen=b.dataset.value===value;b.classList.toggle('selected',chosen);b.setAttribute('aria-pressed',String(chosen));});busyUI();return{selected:value,submitted:false};}
function render(focus=true){
 document.querySelector('#back').hidden=!(step>0&&step<4);document.querySelector('#step-label').hidden=step>0&&step<4;document.querySelector('#step-label').textContent=step===4?'신청 완료':'개인회생 상담 신청';document.querySelector('#step-num').textContent=step===4?'완료':'0'+(step+1);
 document.querySelectorAll('.progress span').forEach((s,i)=>s.classList.toggle('filled',i<=step));document.querySelector('#progress').setAttribute('aria-label',Math.min(step+1,4)+' / 4 단계');document.querySelectorAll('.journey-row').forEach((r,i)=>r.classList.toggle('active',i===(step===0?0:step<3?1:2)));
 if(step===0){body.innerHTML=`<div class="fade"><span class="badge">법무법인 호경 · 개인회생 상담</span><h2 tabindex="-1">혼자 고민하던 채무,<br>상황부터 이야기해 주세요.</h2><p class="sub">질문 두 개에 답하고 상담을 신청하세요.</p>${[['sliders','현재 상황부터 차근차근','채무액과 월 소득을 알려주세요.'],['chat','상담에 필요한 정보만','복잡한 서류 없이 신청할 수 있어요.'],['clock','약 1분이면 신청 완료','연락받을 이름과 번호를 남겨주세요.']].map(([i,t,d])=>`<div class="benefit"><span class="benefit-icon">${icon(i)}</span><div><strong>${t}</strong><small>${d}</small></div></div>`).join('')}</div><div class="spacer"></div><button class="primary" id="next" type="button">상담 신청 시작하기 <span aria-hidden="true">→</span></button><p class="smallnote">입력한 정보는 상담 접수 목적으로 이용됩니다.</p>`;}
 else if(step===1||step===2){const q=QUESTIONS[step-1];body.innerHTML=`<div class="fade"><span class="badge">질문 ${step} / 2</span><h2 tabindex="-1">${q.title}</h2><p class="sub">${q.description}</p><div class="options" role="group" aria-label="${q.title}">${q.options.map(v=>`<button class="option ${answers[step-1]===v?'selected':''}" data-value="${esc(v)}" type="button" aria-pressed="${answers[step-1]===v}"><span class="radio" aria-hidden="true"></span>${v}</button>`).join('')}</div></div><div class="spacer"></div><button class="primary" id="next" type="button">다음 <span aria-hidden="true">→</span></button><p class="smallnote">답변은 다음 단계로 이동할 때 저장돼요.</p>`;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>choose(b.dataset.value));}
 else if(step===3){renderContact(); }else{body.innerHTML=`<div class="success fade"><div class="success-icon" aria-hidden="true" style="font-size:34px">✓</div><span class="badge">접수 완료</span><h2 tabindex="-1">상담 신청이 완료되었어요.</h2><p class="sub">법무법인 호경에 상담 신청이 접수되었습니다.<br>남겨주신 연락처로 상담을 안내해 드립니다.</p><div class="receipt"><div><span>접수 번호</span><strong>${esc(state.reference)}</strong></div><div><span>현재 채무액</span><b>${esc(state.answers[0])}</b></div><div><span>월 소득</span><b>${esc(state.answers[1])}</b></div></div><p class="smallnote">추가 신청 없이 이 화면을 닫으셔도 됩니다.</p></div>`;}
 const nextButton=document.querySelector('#next');if(nextButton)nextButton.onclick=next;busyUI();if(focus)body.querySelector('h2')?.focus({preventScroll:true});
}
document.querySelector('#back').onclick=()=>{if(busy)return;step=Math.max(0,step-1);clearError();render();};
if(document.modelContext?.registerTool){const life=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'stage_campaign_answer',description:'Select an answer on the current question card without saving or submitting the consultation.',inputSchema:{type:'object',properties:{answer:{type:'string'}},required:['answer'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!ready||!input||typeof input.answer!=='string')throw Error('A valid answer is required.');return choose(input.answer);}},{signal:life.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
render(false);init();

